name: app_cudan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-165.1.beta <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_bloc: ^8.1.2
  intl: ^0.17.0
  oauth2: ^2.0.0
  graphql: ^5.1.1
  path_provider:
  dio: ^4.0.6
  multi_select_flutter: ^4.1.2
  badges: ^2.0.3
  dotted_border: ^2.0.0+2
  flutter_svg: ^1.1.5
  pin_code_fields: ^7.4.0
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.3
  file_picker: ^5.0.1
  image_cropper: ^3.0.0
  permission_handler: ^10.0.0
  timeago: ^3.3.0
  flutter_image_compress: ^1.1.1
  cached_network_image: ^3.2.1
  package_info_plus: ^1.4.2
  photo_view: ^0.14.0
  timelines: ^0.1.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  intl_utils: ^2.8.0
  pull_to_refresh: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_widget_from_html: ^0.9.0+1
  open_file_plus: ^3.3.0
  horizontal_blocked_scroll_physics: ^4.0.1
  emoji_dialog_picker: ^1.0.1
  scrollable_positioned_list: ^0.3.5
  flutter_reaction_button: ^2.0.1+2
  flutter_portal: ^1.1.3
  rocket_chat_flutter_connector: ^0.1.4
  web_socket_channel: ^2.0.0
  flutter_emoji: ^2.4.0
  flutter_link_previewer: ^3.2.0
  http_parser: ^4.0.2
  flutter_downloader: ^1.10.1+2
  equatable: ^2.0.5
  loggy: ^2.0.3
  smooth_page_indicator: ^1.0.1
  diacritic: ^0.1.3
  json_dynamic_widget: ^5.1.6+1
  flutter_multi_select_items: ^0.4.2
  uuid: ^3.0.7
  syncfusion_flutter_charts: ^21.1.35
  auto_size_text: ^3.0.0
  top_snackbar_flutter: ^3.0.0+1
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.1
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/demepro.png"
  min_sdk_android: 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/ca/
    - assets/emojies/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
